# Generated by Django 5.2.13 on 2026-06-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Salon Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('list_index', models.FloatField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salonlar',
                'ordering': ['list_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Masa Adı / No')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Kapasite')),
                ('status', models.CharField(choices=[('empty', 'Boş'), ('occupied', 'Dolu'), ('reserved', 'Rezerve'), ('disabled', 'Kullanım Dışı')], default='empty', max_length=10, verbose_name='Durum')),
                ('shape', models.CharField(choices=[('square', 'Kare'), ('round', 'Yuvarlak'), ('rectangle', 'Dikdörtgen')], default='square', max_length=10, verbose_name='Şekil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='dining.room', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Masa',
                'verbose_name_plural': 'Masalar',
                'ordering': ['room', 'name'],
                'unique_together': {('room', 'name')},
            },
        ),
    ]
