# Generated by Django 5.2.13 on 2026-06-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='canvas_height',
            field=models.PositiveIntegerField(default=700, verbose_name='Kanvas Yüksekliği'),
        ),
        migrations.AddField(
            model_name='room',
            name='canvas_width',
            field=models.PositiveIntegerField(default=1000, verbose_name='Kanvas Genişliği'),
        ),
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.PositiveIntegerField(default=80, verbose_name='Yükseklik'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.FloatField(default=20, verbose_name='X Konumu'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.FloatField(default=20, verbose_name='Y Konumu'),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.IntegerField(default=0, verbose_name='Dönüş (derece)'),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.PositiveIntegerField(default=80, verbose_name='Genişlik'),
        ),
    ]
