# Generated by Django 5.2.13 on 2026-06-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_room_canvas_height_room_canvas_width_table_height_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='table',
            name='height',
            field=models.PositiveIntegerField(default=150, verbose_name='Yükseklik'),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.PositiveIntegerField(default=150, verbose_name='Genişlik'),
        ),
    ]
