# Generated by Django 5.2.13 on 2026-06-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_alter_table_unique_together_alter_table_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['room', 'id'], 'verbose_name': 'Masa', 'verbose_name_plural': 'Masalar'},
        ),
    ]
