# Generated by Django 5.2.13 on 2026-04-24 13:06

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS Kullan')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL Kullan')),
                ('default_password', models.CharField(help_text='Şimdilik tüm kullanıcılar için ortak', max_length=255, verbose_name='Varsayılan Mail Şifresi')),
                ('timeout', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail Server Ayarı',
                'verbose_name_plural': 'Mail Server Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('logo_min_light', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('logo_min_dark', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('theme_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_config', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.emailconfig')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings.organization')),
            ],
        ),
    ]
