# Generated by Django 5.2.13 on 2026-06-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dining', '0004_alter_table_options'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('dine_in', 'Masada'), ('takeaway', 'Paket / Gel-Al')], default='dine_in', max_length=10, verbose_name='Sipariş Tipi')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('preparing', 'Hazırlanıyor'), ('served', 'Servis Edildi'), ('paid', 'Ödendi'), ('cancelled', 'İptal')], default='open', max_length=10, verbose_name='Durum')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış Zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dining.table', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ürün Adı')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('preparing', 'Hazırlanıyor'), ('served', 'Servis Edildi'), ('cancelled', 'İptal')], default='pending', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Nakit'), ('card', 'Kredi Kartı'), ('other', 'Diğer')], default='cash', max_length=10, verbose_name='Ödeme Yöntemi')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tutar')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Tahsil Eden')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Adisyon Fişi',
                'verbose_name_plural': 'Adisyon Fişleri',
                'ordering': ['-paid_at'],
            },
        ),
    ]
