# Generated by Django 5.2.13 on 2026-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('preparing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('served', 'Servis Edildi'), ('paid', 'Ödendi'), ('cancelled', 'İptal')], default='open', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('preparing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('served', 'Servis Edildi'), ('cancelled', 'İptal')], default='pending', max_length=10, verbose_name='Durum'),
        ),
    ]
